 project_id  |                                                                          name                                                                          |                              name                               |                                            activity                                            
-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------+------------------------------------------------------------------------------------------------
 LDT939-18   | Gestión y administración de la propiedad inmobiliaria                                                                                                  | Maria Dolores Grova Alvarez                                     | Agencia Inmobiliaria
 LDT879-18   | Comercio al por menor de artículos médicos y ortopédicos en establecimientos especializados                                                            | CIVAGEN, S.A.                                                   | Proveedores Hospitalarios 
 LDT882-18   | Comercio al por menor de textiles en establecimientos especializados                                                                                   | ANA MARIA BAO RODRIGUEZ                                         | TIENDA DE ROPA INFANTIL
 LDT888-18   | Comercio al por mayor de equipos electrónicos y de telecomunicaciones y sus componentes                                                                | OSCAR FERNANDEZ GONZALEZ                                        | ALMACEN MAYORISTA ELECTRONICO-PRODUCTOR AUDIOVISUAL
 LDT892-18   | Otras actividades de impresión y artes gráficas                                                                                                        | JOSE ANTONIO MARTINEZ BOUZA                                     | IMPRENTA
 LDT913-18   | Comercio al por menor en establecimientos no especializados, con predominio en productos alimenticios, bebidas y tabaco                                | JUAN CARLOS DIAZ VARELA                                         | Pescadería
 DDT044-18   | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | ASESORIA FISELA, S.L.                                           | ASESORIA DE EMPRESAS
 LDT914-18   | Actividades odontológicas                                                                                                                              | SOARA CLINICA DENTAL, S.L.                                      | Clínica Dental
 LDT921-18   | Otras actividades de construcción especializada n. c. o. p.                                                                                            | FRANCISCO JAVIER VILLANUEVA ANDION                              | Escayolista
 LDT922-18   | Comercio al por menor de muebles, aparatos de iluminación y otros artículos de uso doméstico en establecimientos especializados                        | SALVADOR JOSE ANTONIO Y JOSE VALVERDE MARTINEZ, C.B.            | 
 LDT927-18   | Actividades de servicios sociales sin alojamiento para personas con discapacidad                                                                       | ASOCIACION P.F.M.P.S. INSTITUTO DE PSICO–PEDIATRIA              | Servicios Sociales
 LDT943-18   | Comercio al por mayor de equipos electrónicos y de telecomunicaciones y sus componentes                                                                | OMAKOON BUSINESS CONSULTING, S.L.                               | Importación / exportación de artículos de electrónica
 LDT963-18   | Mantenimiento y reparación de vehículos de motor                                                                                                       | TALLERES BEMOVIL, S.L.                                          | REPARACION DE AUTOMOVILES
 LDT969-18   | Comercio al por menor de equipos de telecomunicaciones en establecimientos especializados                                                              | COMUNICAMASI, S.L.                                              | Tiendas de telefonia, vodafone
 LDT947-18   | Intermediarios del comercio de productos diversos                                                                                                      | SYSKO TRADING, S.L.                                             | Intermediarios del comercio de productos diversos
 LDT981-18   | Establecimientos de bebidas                                                                                                                            | MIRIAN MARIA PICHARDO MAÑON                                     | Cafetería
 LDT982-18   | Peluquería y otros tratamientos de belleza                                                                                                             | SARA GARCIA GONZALEZ                                            | peluquería 
 LDT989-18   | Educación terciaria no universitaria                                                                                                                   | CURSOS UNIVERSITARIOS INTERNACIONALES MUSICA EN COMPOSTELA      | ESCUELA DE MÚSICA-EDUCACION TERCIARIA NO REGLADA
 LDT902-18   | Otras actividades recreativas y de entretenimiento                                                                                                     | NOR EXPENDE, S.L.                                               | Reparacion, recaudacion y mantenimiento de maquinas recreativas
 LDT938-18   | Revocamiento                                                                                                                                           | Jose Antonio Rodriguez Tasende                                  | MONTAJE DE PLADUR
 LDT886-18   | Comercio al por menor de pescados y mariscos en establecimientos especializados                                                                        | PESCADOS DIEGO BARREIRA, S.L.                                   | Comercio al por menor pescados y mariscos
 LDT891-18   | Producción de aluminio                                                                                                                                 | CANALONES ARGEDO, S.L.                                          | instalación canalones aluminio 
 LDT915-18   | Actividades de apoyo a la agricultura                                                                                                                  | SERVICIOS AGRICOLAS POSE, S.L.                                  | SERVICIO DE MAQUINARIA AGRICOLA
 LDT923-18   | Gestión y administración de la propiedad inmobiliaria                                                                                                  | LEXRU ASESORIA INMOBILIARIA Y CONSULTORIA, S.L.                 | Agencia Inmobiliaria
 LDT900-18   | Comercio al por menor de prendas de vestir en establecimientos especializados                                                                          | Maria Teresa Vazquez Dopico                                     | Tienda de Ropa
 LDT932-18   | Instalaciones eléctricas                                                                                                                               | DIEGO PRIETO MUIÑOS                                             | 
 LDT953-18   | Otro comercio al por menor de artículos nuevos en establecimientos especializados                                                                      | SERVILAR DECORACION E INTERIORISMO, S.C.                        | Decoración
 LDT941-18   | Alojamientos turísticos y otros alojamientos de corta estancia                                                                                         | COPACABANA ALQUILERES, S.L.                                     | Alquiler de apartamentos
 LDT942-18   | Fontanería, instalaciones de sistemas de calefacción y aire acondicionado                                                                              | AIRFRIO VIGO, S.L.                                              | Instaladores de aire acondicionado
 LDT944-18   | Otra educación n. c. o. p.                                                                                                                             | ADELA ROJO DIAZ                                                 |  Enseñanza 
 LDT960-18   | Transporte de mercancías por carretera                                                                                                                 | GAMATRANS SOLUTIONS 2015, S.L.                                  | Transporte de Mercancías
 LDT964-18   | Peluquería y otros tratamientos de belleza                                                                                                             | MARIA CONCEPCION SUAREZ PRADO                                   | PELUQUERIA
 LDT983-18   | Comercio al por menor de carne y productos cárnicos en establecimientos especializados                                                                 | LUIS FERNANDEZ GARCIA                                           | COMERCIO AL POR MENOR DE CARNE Y PRODUCTOS CARNICOS EN ESTABLECIMIENTOS ESPECIALIZADOS
 LDT986-18   | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | EVA INES SARANDESES TARRIO                                      | Asesoría
 LDT881-18   | Hoteles y alojamientos similares                                                                                                                       | LEONARDO COSTA VARELA                                           | HOSTAL
 LDT883-18   | Transporte de mercancías por carretera                                                                                                                 | ANTONIO FERNANDEZ RODRIGUEZ                                     | Paqueteria
 LDT885-18   | Hoteles y alojamientos similares                                                                                                                       | MARIA DEL CARMEN FERNANDEZ PRADA                                | ALBERGUE
 LDT893-18   | Campings                                                                                                                                               | CARBALLOSA, S.L.                                                | Camping
 LDT929-18   | Captación, depuración y distribución de agua                                                                                                           | COMUNIDAD DE REGANTES DE CARAVACA                               | Agricultura
 LDT894-18   | Establecimientos de bebidas                                                                                                                            | CAFE CENTRAL SILAX, S.C.                                        | Cafetería
 LDT924-18   | Otros servicios financieros, excepto seguros y fondos de pensiones n. c. o. p.                                                                         | CENTRO DE FINANCIACION INMOBILIARIA MEJORADA, S.L.              | 
 LDT933-18   | Peluquería y otros tratamientos de belleza                                                                                                             | MARIA FERNANDEZ SOLLA                                           | Peluquería
 LDT945-18   | Restaurantes y puestos de comidas                                                                                                                      | MESON VILLAREJO, S.L.                                           | RESTAURANTE
 LDT949-18   | Comercio al por mayor de animales vivos                                                                                                                | EUSEBIO REVERTE SANCHEZ                                         | Venta de piensos / animales
 LDT951-18   | Encuadernación y servicios relacionados con la misma                                                                                                   | ENCUADERNACIONES SANTIAGO, S.L.                                 | Encuadernaciones y servicios relacionados con la misma
 LDT956-18   | Mantenimiento y reparación de vehículos de motor                                                                                                       | TALLERES LARUFRE, S.L.L.                                        | Taller
 LDT965-18   | Actividades de fotografía                                                                                                                              | JESUS PAZO ALONSO                                               | 
 LDT984-18   | Mantenimiento y reparación de vehículos de motor                                                                                                       | Talleres Fondo, S.L.                                            | Taller mecánico, chapa y pintura
 LDT985-18   | Actividades sindicales                                                                                                                                 | CENTRAL UNITARIA DE TRABALLADORES/AS                            | Sindicato
 LDT990-18   | Comercio al por mayor de pescados, mariscos y otros productos alimenticios                                                                             | ARSANOR, S.L.                                                   | COMERCIO AL POR MAYOR DE PESCADOS, MARISCOS Y OTROS PRODUCTOS ALIMENTICIOS
 LDT1002-18  | Fabricación de calzado                                                                                                                                 | MARIA FERNANDEZ FURTADO MODA Y COMPLEMENTOS S. L.               | Confección de calzado
 LDT995-18   | Fabricación de carpintería metálica                                                                                                                    | CONSTRUCCIONES METALICAS ELIAS J IGLESIAS S.L                   | INSTALACION DE CARPINTERIA
 LDT996-18   | Transporte de mercancías por carretera                                                                                                                 | TRANSMALOSA, S.L.                                               | Transporte de mercancías por carretera
 LDT1005-18  | Otra educación n. c. o. p.                                                                                                                             | SANDRA RODRIGUEZ REIGOSA                                        | Academia de Idiomas
 DDT047-18   | Actividades jurídicas                                                                                                                                  | JOSE LUIS MARTINEZ OLIVARES                                     | Abogado
 LDT1010-18  | Comercio al por mayor de madera, materiales de construcción y aparatos sanitarios                                                                      | MADERAS O FRAGUEIRO, S.L.                                       | Compra venta madera y corcho
 LDT1011-18  | Fabricación de quesos                                                                                                                                  | LACTEOS FARELO, S.L.                                            | Fabricación de Quesos
 LDT1012-18  | Comercio al por mayor de madera, materiales de construcción y aparatos sanitarios                                                                      | COMERCIAL FARELO, S.L.                                          | Venta de Materiales de Construcción
 LDT1016-18  | Asistencia en establecimientos residenciales para personas mayores                                                                                     | STARBRU, S.L.                                                   | Residencia para Personas Mayores
 LDT1013-18  | Agencias de publicidad                                                                                                                                 | HOME COMUNICACION, S.L.                                         | Agencia de publicidad
 LDT1019-18  | Otro comercio al por menor de productos alimenticios en establecimientos especializados                                                                | A TENDA DAS HERBAS, S.C.                                        | Tienda Vegana
 LDT987-18   | Construcción de edificios residenciales                                                                                                                | MECANO SPORT, S.L.                                              | Construcción
 LDT988-18   | Comercio al por mayor de bebidas                                                                                                                       | RICARDO RILO VILLAR                                             | Venta de Bebidas y Tabaco
 LDT991-18   | Comercio al por menor de artículos médicos y ortopédicos en establecimientos especializados                                                            | ANTIA BLANCO BERNARDEZ                                          | 
 LDT884-18   | Instalaciones eléctricas                                                                                                                               | ELECTROFON BERGANTIÑOS, S.L.                                    | INSTALACIONES DE FONTANERIA Y CLIMATIZACION
 LDT887-18   | Hoteles y alojamientos similares                                                                                                                       | MANUEL ANGEL LOPEZ VAZQUEZ                                      | ALBERGUE TURISTICO
 LDT895-18   | Fabricación de otras estructuras de madera y piezas de carpintería y ebanistería para la construcción                                                  | Carpinteria Acuña, S.L.                                         | 
 LDT917-18   | Comercio al por menor de textiles en establecimientos especializados                                                                                   | PIBATEX, S.L.                                                   | Venta al por Mayor Textil - Hogar
 LDT997-18   | Transporte de mercancías por carretera                                                                                                                 | RULADRI-TRANS, S.L.                                             | 
 LDT934-18   | Transporte de mercancías por carretera                                                                                                                 | TRANSPORTES PENA GONZALEZ, S.L.                                 | Transporte de mercancías
 LDT946-18   | Confección de otras prendas de vestir y accesorios                                                                                                     | FRANCISCO LLOR GARCIA Y OTRO CB                                 | Corte y confecciçon
 LDT966-18   | Actividades de fotografía                                                                                                                              | RAQUEL POUSA VAZQUEZ                                            | Fotografía
 DDT046-18   | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | MEDINA Y ORGAZ, S.L.                                            | Asesoría
 LDT998-18   | Actividades de juegos de azar y apuestas                                                                                                               | A MILLONARIA LOTARIAS, S. L.                                    | Agencia de Loterias
 LDT1014-18  | Comercio al por menor de prendas de vestir en establecimientos especializados                                                                          | BESANDO RANAS, S.C.                                             | Tienda de Ropa
 LDT1000-18  | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | XESTION ARCADE 2012, S.L.P.                                     | Asesoría
 LDT1001-18  | Establecimientos de bebidas                                                                                                                            | ILDA GONZALEZ BLANCO                                            | 
 LDT1003-18  | Gestión y administración de la propiedad inmobiliaria                                                                                                  | LOURDES ARTIACH CARALT                                          | Inmobiliaria
 LDT1006-18  | Restaurantes y puestos de comidas                                                                                                                      | MARIELA GISELA CAMPEÑI SCALISE                                  | Restaurante
 DDT048-18   | Gestión de instalaciones deportivas                                                                                                                    | XESTION DE ACTIVIDADES DEPORTIVAS E ESPECTACULOS, S.L.          | Gestión de Instalaciones Deportivas
 LDT1018-18  | Transporte terrestre urbano y suburbano de pasajeros                                                                                                   | AUTOCARES OFELIA E SOUTO CASTRO, S.L.                           | Transporte de Pasajeros
 DDT042-18   | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | XESTUI, S.L.                                                    | Asesoría
 LDT918-18   | Fontanería, instalaciones de sistemas de calefacción y aire acondicionado                                                                              | PELETEIRO INSTALACIONES S. L.                                   | Instalaciones, fontanería, calefacción 
 LDT920-18   | Comercio al por mayor de pescados, mariscos y otros productos alimenticios                                                                             | PESCADOS CASA OSCAR S.L.                                        | 
 LDT935-18   | Comercio al por menor de muebles, aparatos de iluminación y otros artículos de uso doméstico en establecimientos especializados                        | MUSICAL ROSALINO, S.L.                                          | Venta de Instrumentos Musicales
 LDT889-18   | Fabricación de carpintería metálica                                                                                                                    | JOSE IGNACIO FRAGA FERNANDEZ                                    | Carpintería metálica y mantenimientos 
 LDT890-18   | Comercio al por menor en establecimientos no especializados, con predominio en productos alimenticios, bebidas y tabaco                                | DISAURIA, S.L.                                                  | Distribución de Bebidas
 LDT896-18   | Comercio al por menor de aparatos electrodomésticos en establecimientos especializados                                                                 | Master Fernan, S.L.                                             | CONSTRUCCION DE EDIFICIOS RESIDENCIALES
 LDT912-18   | Educación primaria                                                                                                                                     | COLEGIO LUIS VIVES                                              | Colegio Concertado
 LDT950-18   | Construcción de edificios residenciales                                                                                                                | ANDAMIOS GALLEGOS, S.L.                                         | Montaje de Andamios y Construcción
 LDT952-18   | Fabricación de otras estructuras de madera y piezas de carpintería y ebanistería para la construcción                                                  | PABLO PINTOR LARRAN                                             | CARPINTERO 
 LDT958-18   | Otra educación n. c. o. p.                                                                                                                             | ENSINO PROFESIONAL GALEGO, S.L.                                 | Enseñanza y formación no reglada
 LDT967-18   | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | MEDINA Y ORGAZ, S.L.                                            | Asesoría
 LDT992-18   | Hoteles y alojamientos similares                                                                                                                       | MARIA LUISA ECHEZARRAGA DIAZ                                    | Hoteles
 LDT999-18   | Comercio al por menor de productos cosméticos e higiénicos en establecimientos especializados                                                          | DOLORES FANDIÑO MIRANDA                                         | Comercio al por menor de productos de peluquería 
 LDT1004-18  | Comercio al por mayor, no especializado, de productos alimenticios, bebidas y tabaco                                                                   | BECOGALIA AFINES, S.L.                                          | Venta de Productos Alimenticios
 LDT1007-18  | Actividades de los clubes deportivos                                                                                                                   | S.C.D. AMISTAD                                                  | Sociedad Cultural Deportiva
 LDT1015-18  | Comercio al por menor de carne y productos cárnicos en establecimientos especializados                                                                 | MARIA DEL CARMEN ROUCO FERNANDEZ                                | Carnicería
 LDT1017-18  | Fabricación de otros muebles                                                                                                                           | ESPERON BESADA, S.L.                                            | Fábrica de muebles
 LDT1022-18  | Mantenimiento y reparación de vehículos de motor                                                                                                       | AUTOS BUENOS AIRES GALICIA, S.L.                                | CONCESIONARIO (taller y venta)
 LDT925-18   | Servicios técnicos de ingeniería y otras actividades relacionadas con el asesoramiento técnico                                                         | BALTASAR GARCIA BENITEZ                                         | 
 LDT897-18   | Comercio al por menor de combustible para la automoción en establecimientos especializados                                                             | E.S. GAS SUR SERVICIOS, S.L.                                    | Gasolinera
 LDT911-18   | Comercio al por menor de flores, plantas, semillas, fertilizantes, animales de compañía y alimentos para los mismos en establecimientos especializados | MARIA LUZ LANDIN LAMAS                                          | 
 LDT919-18   | Peluquería y otros tratamientos de belleza                                                                                                             | MARIA ANGELA FERVENZA ALVAREZ                                   | Peluquería
 LDT928-18   | Actividades de los gimnasios                                                                                                                           | ANTONIO GONZALEZ PEREZ                                          | Gimnasio
 LDT936-18   | Comercio al por mayor de bebidas                                                                                                                       | ARGELIO FREIJE FERNANDEZ                                        | Almacén y Venta de Vinos
 LDT940-18   | Alojamientos turísticos y otros alojamientos de corta estancia                                                                                         | RESIDENCIAL SEGURA, S.A.                                        | Alquiler de apartamentos
 LDT954-18   | Comercio al por menor de combustible para la automoción en establecimientos especializados                                                             | CARBURANTES LAS CUMBRES, S.L.                                   | Gasolinera
 LDT955-18   | Comercio al por menor de combustible para la automoción en establecimientos especializados                                                             | E.S. LAS CUMBRES, S.L.                                          | Gasolinera
 LDT962-18   | Fontanería, instalaciones de sistemas de calefacción y aire acondicionado                                                                              | ICOFRIO, S.L.                                                   | Instalación de Equipos 
 DDT045-18   | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | GESTION EMPRESARIAL LA GUARDIA, SL                              | ACTIVIDADES DE CONTABILIDAD, TENEDURIA DE LIBROS, AUDITORIA Y ASESORIA FISCAL
 LDT968-18   | Construcción de edificios residenciales                                                                                                                | Genaro Borrajo e Hijos, S.L.                                    | 
 LDT993-18   | Hoteles y alojamientos similares                                                                                                                       | RIO DE LOIBA S.L.                                               | hoteles
 LDT980-18   | Mantenimiento y reparación de vehículos de motor                                                                                                       | MECANICA ANSEMIL, S.C.                                          | 
 LDT1008-18  | Otro comercio al por menor en establecimientos no especializados                                                                                       | EFECTOS NAVALES JESUS BETANZOS, S.L.                            | Efectos Navales y Pesca Deportiva 
 LDT1009-18  | Transporte de mercancías por carretera                                                                                                                 | DAYJO LOGISTICA, S.L.                                           | Transporte de mercancías por carretera
 LDT1020-18  | Comercio al por menor de muebles, aparatos de iluminación y otros artículos de uso doméstico en establecimientos especializados                        | AMUEBLA PONTEVEDRA, S.L.                                        | Tienda de Muebles 
 LDT898-18   | Comercio al por mayor de maquinaria, equipos y suministros agrícolas                                                                                   | Jumava Maquinaria, S.L.                                         | FABRICACION DE MAQUINARIA, EQUIPOS Y SUMINISTROS AGRICOLAS
 LDT904-18   | Comercio al por menor de ferretería, pintura y vidrio en establecimientos especializados                                                               | ANTONIO FERNANDEZ RODRIGUEZ                                     | Ferretería
 LDT905-18   | Otras actividades de consultoría de gestión empresarial                                                                                                | EMO SECURUS, S.L.                                               | Asesoramiento y gestiones varias
 LDT907-18   | Tratamiento y eliminación de residuos no peligrosos                                                                                                    | Tratamientos Ecologicos del Noroeste, S.L.                      | 
 LDT908-18   | Transporte de mercancías por carretera                                                                                                                 | QUILUCHO, S.L.                                                  | TRANPORTE DE MERCANCIAS
 LDT930-18   | Otro comercio al por menor de artículos nuevos en establecimientos especializados                                                                      | SARA FERNANDEZ EIRE                                             | 
 LDT937-18   | Fabricación de pan y de productos frescos de panadería y pastelería                                                                                    | OLGA ESCANEO GONZALEZ                                           | Panadería 
 LDT948-18   | Comercio al por mayor de animales vivos                                                                                                                | OVICAPIEN, S.L.                                                 | Ganado 
 LDT957-18   | Actividades de jardinería                                                                                                                              | ORBALLO XARDINS, S.L.                                           | Jardinería
 LDT970-18   | Otro comercio al por menor en establecimientos no especializados                                                                                       | MASITIENDAS, S.L.                                               | Tiendas de Telefonía Vodafone
 LDT973-18   | Comercio al por menor de pescados y mariscos en establecimientos especializados                                                                        | ROCIO LOSADA DIAZ                                               | Pescadería
 LDT994-18   | Restaurantes y puestos de comidas                                                                                                                      | A BARROLA RESTAURANTE, S.L.                                     | Restaurante
 LDT899-18   | Comercio al por menor de prendas de vestir en establecimientos especializados                                                                          | Miguel Lopez Vazquez                                            | Tienda de Ropa
 LDT910-18   | Preparación, curtido y acabado del cuero; preparación y teñido de pieles                                                                               | PADRONESA INDUSTRIAL DE CURTIDOS, S.A.                          | Preparación, curtido y acabado del cuero.
 LDT959-18   | Comercio al por menor de combustible para la automoción en establecimientos especializados                                                             | E.S. CRUZ DA VEIGA, S.L.                                        | Gasolinera, Gasocentro, Comercio al por menor de alimentación, Restaurante, Café Bar y Pensión
 LDT971-18   | Fontanería, instalaciones de sistemas de calefacción y aire acondicionado                                                                              | LUCIA FERNANDEZ SANGRADOR                                       | 
 LDT1021-18  | Comercio al por mayor de muebles, alfombras y aparatos de iluminación                                                                                  | CELSO TOME, S.L.                                                | Distribuidor de Muebles 
 LDT1023-18  | Comercio al por mayor de azúcar, chocolate y confitería                                                                                                | DULCES TUI, S.L.                                                | 
 LDT1046-18  | Reparación y mantenimiento naval                                                                                                                       | REPARACIONES DEL ATLANTICO, S.L.                                | Reparación de Buques
 LDT972-18   | Hoteles y alojamientos similares                                                                                                                       | LA CASONA DE SARRIA COMPLEJO TURISTICO, S.L.                    | Pension con comidas  y alojamiento
 LDT978-18   | Otra educación n. c. o. p.                                                                                                                             | LUDOTECA FLIPY, C.B.                                            | Ludoteca
 LDT1028-18  | Otras actividades recreativas y de entretenimiento                                                                                                     | LUISA ESTEVEZ FERNANDEZ                                         | Clases de Baile
 DDT050-18   | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | GESTRADOC, S. L                                                 | Asesoría
 LDT1031-18  | Corte, tallado y acabado de la piedra                                                                                                                  | MARMOLES RAIMAR, S.L.                                           | Marmolería
 LDT1032-18  | Otro comercio al por menor de artículos nuevos en establecimientos especializados                                                                      | MATILDE CARRILLO DE ALBORNOZ POYATOS                            | Comercialización de impresoras y etiquetas
 DDT051-18   | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | IGSA ASESORES DE EMPRESA, S.L.                                  | Asesoría de empresas
 LDT1033-18  | Otra educación n. c. o. p.                                                                                                                             | PEREZ ALONSO, C.B.                                              | Academia de inglés
 LDT1040-18  | Mantenimiento y reparación de vehículos de motor                                                                                                       | Talleres Rodriguez Lois, S. L.                                  | Taller Mecánico
 LDT1034-18  | Otra educación n. c. o. p.                                                                                                                             | LANGUAGE ZONE, S.L.                                             | Academia de idiomas
 LDT1056-18  | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | ALBAGEST GESTION INTEGRAL, S.L.                                 | 
 LDT903-18   | Otro acabado de edificios                                                                                                                              | PINTURAS Y DECORACIONES O ROSAL, S.L.                           | Reformas
 LDT974-18   | Servicios técnicos de ingeniería y otras actividades relacionadas con el asesoramiento técnico                                                         | ORDENACION TERRITORIAL, INFRAESTRUCTURAS E MEDIO AMBIENTE, S.L. | 
 LDT1025-18  | Actividades de diseño especializado                                                                                                                    | CRISTALERIA ROMERA, S.L.                                        | Carpintería, Persianas y Marquetería
 LDT1029-18  | Gestión de instalaciones deportivas                                                                                                                    | DEPORTE Y LUCHA, S.L.                                           | Fitness, Artes Marciales, Crossfit y Padel
 LDT1035-18  | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | GESTORIA ADMINISTRATIVA SAN JOSE, S.L.                          | Asesoría
 LDT1041-18  | Actividades de medicina general                                                                                                                        | IÑIGO SANCHEZ DE URBINA                                         | Consulta médica
 LDT1047-18  | Comercio al por mayor de pescados, mariscos y otros productos alimenticios                                                                             | MARISCOS INES, S.L.                                             | Venta al por Mayor de Pescado
 LDT1053-18  | Explotación de ganado bovino para la producción de leche                                                                                               | GRANXA BRUZOS, S.L.                                             | Explotación de Ganado
 LDT1058-18  | Fabricación de carpintería metálica                                                                                                                    | CONSTRUCCIONES METALICAS PEREZ TABOADA, S.C.                    | Carpintería Metálica
 LDT1068-18  | Comercio al por menor de prendas de vestir en establecimientos especializados                                                                          | PRONTOS MODA DE LUGO, S.L                                       | Fabrica textil
 LDT906-18   | Otras actividades asociativas n. c. o. p.                                                                                                              | ASOCIACION GALLEGA DE EMPRESAS OPERADORAS                       | Asociación de empresas
 DDT043-18   | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | LAGO GARCIA ASESORIA, SL                                        | Asesoría
 LDT976-18   | Construcción de edificios residenciales                                                                                                                | CONSTRUCCIONES PEREA Y MUÑOZ, S.L.                              | CONSTRUCCIÓN
 LDT1026-18  | Comercio al por mayor de pescados, mariscos y otros productos alimenticios                                                                             | LONXA NOVA, S.L.                                                | Mayorista de Pescados
 LDT1030-18  | Gestión de instalaciones deportivas                                                                                                                    | DEPORTE Y COMUNIDAD, S.L.                                       | Fitness, Artes Marciales, Crossfit y Padel
 DDT049-18   | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | GESTORIA ADMINISTRATIVA SAN JOSE, S.L.                          | Asesoría
 LDT1042-18  | Actividades de servicios sociales sin alojamiento para personas con discapacidad                                                                       | REBECA DEL RIO RODRIGUEZ                                        | centro de dia 
 LDT1048-18  | Comercio al por menor de periódicos y artículos de papelería en establecimientos especializados                                                        | MARIA DEL CARMEN HERNANDEZ RUBIO                                | Copistería
 LDT1054-18  | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | SAMPAYO Y CARREIRA ASESORES, S.L.                               | Asesoría Fiscal, Laboral y contable
 LDT1059-18  | Construcción de edificios residenciales                                                                                                                | BELARMINO FERNANDEZ CONSTRUCCIONES, S.L.                        | Construcción
 LDT977-18   | Demolición                                                                                                                                             | EXCAVACIONES PEREA RAMIREZ, S.L.N.E.                            | CONTRUCCIÓN
 LDT1027-18  | Restaurantes y puestos de comidas                                                                                                                      | DISTRIBUIDORA VA&DY, S.L.                                       | Restaurante
 LDT1036-18  | Pintura y acristalamiento                                                                                                                              | FRAMARK FENE, S.L.                                              | PINTURA Y ACRISTALAMIENTO
 LDT1043-18  | Alojamientos turísticos y otros alojamientos de corta estancia                                                                                         | LUIS MONTES SAENZ                                               | 
 LDT1044-18  | Servicios técnicos de ingeniería y otras actividades relacionadas con el asesoramiento técnico                                                         | ARIUS INVERS, S.L.                                              | Servicios Técnicos de Ingeniería 
 LDT1049-18  | Comercio al por menor de carne y productos cárnicos en establecimientos especializados                                                                 | MARIA DEL CARMEN TABOADA VARELA                                 | Carnicería y Charcutería
 LDT1055-18  | Mantenimiento y reparación de vehículos de motor                                                                                                       | VIVEIRO AUTOMOCION IGLOUCO, S.L.                                | Concesionario y Taller de Coches
 LDT1057-18  | Peluquería y otros tratamientos de belleza                                                                                                             | MARIA ISABEL TORRES ALVAREZ                                     | Peluqueria
 LDT1069-18  | Portales web                                                                                                                                           | WANAMOS ECOMMERCE S.L.                                          | DISEÑO DE PÁGINAS WEB
 LDT975-18   | Estudios de mercado y realización de encuestas de opinión pública                                                                                      | LORENZO Y LAGO PROYECTOS, S.L.                                  | Estudios de Mercado
 LDT1037-18  | Otras instalaciones en obras de construcción                                                                                                           | ANGEL FERNANDEZ GONZALEZ, S.A.                                  | Fabricación, Venta e Instalación de Rótulos
 LDT1045-18  | Actividades de contabilidad, teneduría de libros, auditoría y asesoría fiscal                                                                          | MARIA JESUS BUSTELO GONZALEZ                                    | Contable
 LDT1050-18  | Fabricación de otros muebles                                                                                                                           | LAX SOFA TAPICEROS, S.L.                                        | Venta y Fabricación de Muebles
 LDT1060-18  | Corte, tallado y acabado de la piedra                                                                                                                  | MARMOLES JUNI, S.L.                                             | Marmolería
 LDT1062-18  | Fabricación de envases y embalajes de plástico                                                                                                         | DENSOPLAST, S.L.                                                | 
 LDT979-18   | Actividades de juegos de azar y apuestas                                                                                                               | RECREATIVOS CASTIÑEIRAS, S.L.                                   | Actividades de juegos de azar y apuestas y alquiler de locales
 LDT1038-18  | Ensayos y análisis técnicos                                                                                                                            | ANFER CORPORATIVA, S.L.                                         | Oficina Técnica
 LDT1024-18  | Otros servicios relacionados con las tecnologías de la información y la informática                                                                    | JESUS PEREZ ALONSO                                              | Informática Profesional
 LDT1051-18  | Actividades de consultoría informática                                                                                                                 | NETEX LEARNING IBERIA, S.L.                                     | Desarrollo Software
 LDT1063-18  | Restaurantes y puestos de comidas                                                                                                                      | JIANCHU ZHOU                                                    | Restaurante
 LDT1065-18  | Comercio al por menor de flores, plantas, semillas, fertilizantes, animales de compañía y alimentos para los mismos en establecimientos especializados | MARIA ESPERANZA ARRIBAS GORIS                                   | BAZAR
 LDT1039-18  | Comercio al por menor en establecimientos no especializados, con predominio en productos alimenticios, bebidas y tabaco                                | JESUS GOMEZ SOÑORA                                              | Autoservicio. Comercio al por menor de productos alimenticios, bebidas y tabaco
 LDT1052-18  | Mantenimiento y reparación de vehículos de motor                                                                                                       | OSCAR FRECHA VAZQUEZ                                            | Taller Mecánico
 LDT1066-18  | Otro comercio al por menor en establecimientos no especializados                                                                                       | CROMOLY, S.L.L.                                                 | 
(191 rows)

